---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tasks:
    - debug: var=homebrew_update
    - debug: var=homebrew_upgrade
  roles:
    - role: homebrew
      tags: brew
    - role: homebrew-cask
      tags: brew
    - role: pip-packages
      tags: pip
    - name: bashrc
      tags: bash
    - name: spf13-vim
      tags: spf13
    - name: s3ql
      tags: s3ql
