---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - role: homebrew
      tags: brew
    - role: homebrew-cask
      tags: brew
    - name: bashrc
      tags: bash
    - name: spf13-vim
      tags: spf13
